#+title: 图形学系列——OpenGL
#+author: jask
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage{ctex}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \setmainfont{Noto Sans CJK SC}
#+LATEX_HEADER: \usepackage[a4paper,margin=1in]{geometry}
#+OPTIONS: toc:nil
#+mathspec: true

* 画出来三角形！
画一下流程

简单地说，OpenGL画出一个三角形无外乎：glfw准备，glad准备，顶点着色器、片段着色器编译，顶点数据、顶点属性准备，数据绑定，事件循环，终结。

#+begin_src plantuml :file images/RenderingProcess.png
@startuml OpenGL Triangle Drawing Process
participant "Application" as App
participant "GLFW" as GLFW
participant "GLAD" as GLAD
participant "Shader" as Shader
participant "Buffer" as Buffer

== Initialization Phase ==
App -> GLFW : glfwInit()
App -> GLFW : glfwCreateWindow()
App -> GLAD : gladLoadGLLoader()

== Shader Preparation ==
App -> Shader : glCreateShader(GL_VERTEX_SHADER)
App -> Shader : glCreateShader(GL_FRAGMENT_SHADER)
App -> Shader : glCreateProgram()
App -> Shader : glLinkProgram()

== Buffer Configuration ==
App -> Buffer : glGenVertexArrays(VAO)
App -> Buffer : glGenBuffers(VBO)
App -> Buffer : glGenBuffers(EBO)
App -> Buffer : glBindVertexArray()
App -> Buffer : glBufferData(vertices)
App -> Buffer : glBufferData(indices)
App -> Buffer : glVertexAttribPointer()

== Render Loop ==
loop while !glfwWindowShouldClose()
    App -> GLFW : glfwWindowShouldClose()
    App -> Buffer : glClear()
    App -> Shader : glUseProgram()
    App -> Buffer : glBindVertexArray()
    App -> Buffer : glDrawElements()
    App -> GLFW : glfwSwapBuffers()
end

== Cleanup ==
App -> Buffer : glDeleteVertexArrays()
App -> Buffer : glDeleteBuffers()
App -> Shader : glDeleteProgram()
App -> GLFW : glfwTerminate()

@enduml

#+end_src

** 渲染流程
涉及到渲染流程上，比如说一个三角形可能太过简单，怎么才能渲染两个三角形、渲染两个重叠的三角形？这些就涉及到顶点数据和索引数组。

#+begin_src cpp
    float vertices[] = { 
        -0.9f,-0.5f,0.0f,  
        -0.0f,-0.5f,0.0f,
        -0.45f,0.5f,0.0f,
        0.0f,-0.5f,0.0f, 
        0.9f,-0.5f,0.0f, 
        0.45f,0.5f,0.0f  
    };                   
#+end_src
这里给出来了两个三角形对应的6个点，那么就可以通过glDrawArrays来依次渲染6个点。

渲染两个不同颜色的三角形就意味着要使用不同的片段着色器，片段着色器使用的vec4是一个RGBA格式的四元组，最后一个A代表透明度。

也可以使用不同的VAO和VBO来渲染。
* 着色器
上面是快速地过一遍OpenGL的流程，这里是深入学习一下着色器。
** GLSL
着色器的开头总是要声明版本，接着是输入和输出变量、uniform和main函数。每个着色器的入口点都是main函数，在这个函数中我们处理所有的输入变量，并将结果输出到输出变量中。
#+begin_src c
#version version_number
in type in_variable_name;
in type in_variable_name;

out type out_variable_name;

uniform type uniform_name;

void main()
{
  // 处理输入并进行一些图形操作
  ...
  // 输出处理过的结果到输出变量
  out_variable_name = weird_stuff_we_processed;
}
#+end_src
输入变量叫做顶点属性。我们能声明的顶点属性是有上限的，它一般由硬件来决定。OpenGL确保至少有16个包含4分量的顶点属性可用，但是有些硬件或许允许更多的顶点属性，你可以查询GL_MAX_VERTEX_ATTRIBS来获取具体的上限。
** 数据类型
GLSL中包含C等其它语言大部分的默认基础数据类型：int、float、double、uint和bool。GLSL也有两种容器类型，它们会在这个教程中使用很多，分别是向量(Vector)和矩阵(Matrix)。

***** 向量
vec, bvec, ivec, uvec, dvec对应的类型参考前缀（vec是float vector, bvec是bool vector）。

向量获取分量可以用.x/.y/.z./.w也可以使用重组，也就是：
#+begin_src c
vec2 someVec;
vec4 differentVec = someVec.xyxx;
vec3 anotherVec = differentVec.zyw;
vec4 otherVec = someVec.xxxx + anotherVec.yxzy;
#+end_src

***** 输入与输出
GLSL定义了in和out关键字专门来实现这个目的。每个着色器使用这两个关键字设定输入和输出，只要一个输出变量与下一个着色器阶段的输入匹配，它就会传递下去。但在顶点和片段着色器中会有点不同。

+ 顶点着色器接受的是从顶点数据中直接传入的输入，使用location来管理变量。
+ 片段着色器需要用一个vec4颜色输出变量，因为片段着色器需要生成一个最终输出的颜色。

如果打算从一个着色器向另一个着色器发送数据，就必须在发送方着色器中声明一个输出，在接收方着色器中声明一个类似的输入。当名称和类型都一致是OpenGL会把两个变量链接在一起，就可以发送数据了。

***** Uniform
Uniform是另一种从我们的应用程序在 CPU 上传递数据到 GPU 上的着色器的方式，但uniform和顶点属性有些不同。
+ 首先，uniform是全局的(Global)。全局意味着uniform变量必须在每个着色器程序对象中都是独一无二的，而且它可以被着色器程序的任意着色器在任意阶段访问。
+ 第二，无论你把uniform值设置成什么，uniform会一直保存它们的数据，直到它们被重置或更新。

使用只需要在着色器使用uniform关键字并带上类型和名称。

有了Uniform，我们就可以在运行期修改图形的着色了。（相关API：glUniform4f, glGetUniformLocation）。

注意，查询uniform地址不要求你之前使用过着色器程序，但是更新一个uniform之前你必须先使用程序（调用glUseProgram)，因为它是在当前激活的着色器程序中设置uniform的。

***** 更多属性
颜色数据也可以被加入到顶点数据中，这时候需要修改顶点着色器中的layout，讲location=1的位置设置为颜色属性。由于添加了一个新的顶点属性，并且更新了VBO的内存，就必须重新配置顶点属性指针。
* 纹理
为了能够把纹理映射(Map)到三角形上，我们需要指定三角形的每个顶点各自对应纹理的哪个部分。这样每个顶点就会关联着一个纹理坐标(Texture Coordinate)，用来标明该从纹理图像的哪个部分采样（译注：采集片段颜色）。之后在图形的其它片段上进行片段插(Fragment Interpolation)。
** 纹理过滤
纹理坐标不依赖于分辨率(Resolution)，它可以是任意浮点值，所以OpenGL需要知道怎样将纹理像素(Texture Pixel，也叫Texel），映射到纹理坐标。当你有一个很大的物体但是纹理的分辨率很低的时候这就变得很重要了。你可能已经猜到了，OpenGL也有对于纹理过滤(Texture Filtering)的选项。纹理过滤有很多个选项，但是现在我们只讨论最重要的两种：GL_NEAREST和GL_LINEAR。
** 多级渐远纹理
多级渐远纹理背后的理念很简单：距观察者的距离超过一定的阈值，OpenGL会使用不同的多级渐远纹理，即最适合物体的距离的那个。由于距离远，解析度不高也不会被用户注意到。同时，多级渐远纹理另一加分之处是它的性能非常好。OpenGL对应的API叫做glGenerateMipmap。
** 加载与创建纹理
可以使用第三方图像加载库。图像加载之后，以char*的形式，通过glTex相关的API进行采样，之后就可以通过纹理坐标加载进去。
** 纹理环绕方式
| 环绕方式 | 描述 |
| GL_REPEAT | 对纹理的默认行为，重复纹理图像 | 
| GL_MIRRORED_REPEAT | 每次重复的图像镜像放置 |
| GL_CLAMP_TO_EDGE | 纹理坐标被约束在0-1之间，超出部分会重复纹理边缘 |
| GL_CLAMP_TO_BORDER  | 超出的坐标为用户指定的边缘颜色 |
** 纹理单元
使用glUniform1i，我们可以给纹理采样器分配一个位置值，这样的话我们能够在一个片段着色器中设置多个纹理。一个纹理的位置值通常称为一个纹理单元(Texture Unit)。一个纹理的默认纹理单元是0，它是默认的激活纹理单元。

纹理单元的主要目的是让我们在着色器中可以使用多于一个的纹理。

* 变换
** 向量
向量最基本的定义就是一个方向。或者更正式的说，向量有一个方向(Direction)和大小(Magnitude，也叫做强度或长度)。
** 旋转
在3D空间中旋转需要定义一个角和一个旋转轴(Rotation Axis)。物体会沿着给定的旋转轴旋转特定角度。
传参数时可以使用glUniformMatrix4fv。
注意一点，OpenGL中的矩阵操作是从右到左的，也就是是说，这样的代码：
#+BEGIN_SRC c++
  glm::mat4 trans = glm::mat4(1.0f);                            
  //trans = glm::translate(trans, glm::vec3(0.5f, -0.5f, 0.0f));
  trans = glm::rotate(trans, (float)glfwGetTime(),glm::vec3(0.0f, 0.0f, 1.0f));             
  trans = glm::translate(trans, glm::vec3(0.5f, -0.5f, 0.0f));    
#+END_SRC
执行的是先平移再旋转，交换rotate和translate的位置，就是先旋转后平移。

* 坐标系统
为了将坐标从一个坐标系变换到另一个坐标系，我们需要用到几个变换矩阵，最重要的几个分别是模型(Model)、观察(View)、投影(Projection)三个矩阵。

我们的顶点坐标起始于局部空间(Local Space)，在这里它称为局部坐标(Local Coordinate)，它在之后会变为世界坐标(World Coordinate)，观察坐标(View Coordinate)，裁剪坐标(Clip Coordinate)，并最后以屏幕坐标(Screen Coordinate)的形式结束。
** Entering Three Dimension!
***** ZBuffer
OpenGL存储它的所有深度信息于一个Z缓冲(Z-buffer)中，也被称为深度缓冲(Depth Buffer)。GLFW会自动为你生成这样一个缓冲（就像它也有一个颜色缓冲来存储输出图像的颜色）。深度值存储在每个片段里面（作为片段的z值），当片段想要输出它的颜色时，OpenGL会将它的深度值和z缓冲进行比较，如果当前的片段在其它片段之后，它将会被丢弃，否则将会覆盖。这个过程称为深度测试(Depth Testing)，它是由OpenGL自动完成的。

然而，如果我们想要确定OpenGL真的执行了深度测试，首先我们要告诉OpenGL我们想要启用深度测试；它默认是关闭的。我们可以通过glEnable函数来开启深度测试。glEnable和glDisable函数允许我们启用或禁用某个OpenGL功能。这个功能会一直保持启用/禁用状态，直到另一个调用来禁用/启用它。
***** Camera
获取摄像机位置很简单。摄像机位置简单来说就是世界空间中一个指向摄像机位置的向量。

这里指的是摄像机指向哪个方向。现在我们让摄像机指向场景原点：(0, 0, 0)。还记得如果将两个矢量相减，我们就能得到这两个矢量的差吗？用场景原点向量减去摄像机位置向量的结果就是摄像机的指向向量。由于我们知道摄像机指向z轴负方向，但我们希望方向向量(Direction Vector)指向摄像机的z轴正方向。如果我们交换相减的顺序，我们就会获得一个指向摄像机正z轴方向的向量。
***** 右轴
我们需要的另一个向量是一个右向量(Right Vector)，它代表摄像机空间的x轴的正方向。为获取右向量我们需要先使用一个小技巧：先定义一个上向量(Up Vector)。接下来把上向量和第二步得到的方向向量进行叉乘。两个向量叉乘的结果会同时垂直于两向量，因此我们会得到指向x轴正方向的那个向量。
***** 上轴
现在我们已经有了x轴向量和z轴向量，获取一个指向摄像机的正y轴向量就相对简单了：我们把右向量和方向向量进行叉乘。
***** LookAt
使用矩阵的好处之一是如果你使用3个相互垂直（或非线性）的轴定义了一个坐标空间，你可以用这3个轴外加一个平移向量来创建一个矩阵，并且你可以用这个矩阵乘以任何向量来将其变换到那个坐标空间。这正是LookAt矩阵所做的，现在我们有了3个相互垂直的轴和一个定义摄像机空间的位置坐标，我们可以创建我们自己的LookAt矩阵了。
#+begin_export latex
\[
LookAt=
\begin{bmatrix}
R_x & R_y &  R_z & 0 \\
U_x & U_y & U_z & 0 \\
D_x & D_y & D_z & 0 \\
0   & 0   & 0   & 1 
\end{bmatrix}
\times
\begin{bmatrix}
1 & 0 & 0 & -P_x \\
0 & 1 & 0 & -P_y \\
0 & 0 & 1 & -P_z \\
0 & 0 & 0 & 1
\end{bmatrix}
\]
#+end_export

其中R是右向量，U是上向量，D是方向向量P是摄像机位置向量。注意，位置向量是相反的，因为我们最终希望把世界平移到与我们自身移动的相反方向。

GLM已经提供了这些支持。我们要做的只是定义一个摄像机位置，一个目标位置和一个表示世界空间中的上向量的向量（我们计算右向量使用的那个上向量）。接着GLM就会创建一个LookAt矩阵，我们可以把它当作我们的观察矩阵。
***** 视角移动
视角移动是依靠的欧拉角。欧拉角(Euler Angle)是可以表示3D空间中任何旋转的3个值，由莱昂哈德·欧拉(Leonhard Euler)在18世纪提出。一共有3种欧拉角：俯仰角(Pitch)、偏航角(Yaw)和滚转角(Roll)。

俯仰角是描述我们如何往上或往下看的角，可以在第一张图中看到。第二张图展示了偏航角，偏航角表示我们往左和往右看的程度。滚转角代表我们如何翻滚摄像机，通常在太空飞船的摄像机中使用。每个欧拉角都有一个值来表示，把三个角结合起来我们就能够计算3D空间中任何的旋转向量了。


* 光照
OpenGL的光照使用的是简化的模型，对现实的情况进行近似，这样处理起来会更容易一些。

其中一个模型被称为风氏光照模型(Phong Lighting Model)。风氏光照模型的主要结构由3个分量组成：环境(Ambient)、漫反射(Diffuse)和镜面(Specular)光照。
***** 环境光照
即使在黑暗的情况下，世界上通常也仍然有一些光亮（月亮、远处的光），所以物体几乎永远不会是完全黑暗的。为了模拟这个，我们会使用一个环境光照常量，它永远会给物体一些颜色。
***** 漫反射光照
模拟光源对物体的方向性影响(Directional Impact)。它是风氏光照模型中视觉上最显著的分量。物体的某一部分越是正对着光源，它就会越亮。
+ 法向量：一个垂直于顶点表面的向量。
+ 定向的光线：作为光源的位置与片段的位置之间向量差的方向向量。为了计算这个光线，我们需要光的位置向量和片段的位置向量。

***** 镜面光照
模拟有光泽物体上面出现的亮点。镜面光照的颜色相比于物体的颜色会更倾向于光的颜色。
***** 法线
法向量是一个垂直于顶点表面的（单位）向量。由于顶点本身并没有表面（它只是空间中一个独立的点），我们利用它周围的顶点来计算出这个顶点的表面。

法向量只是一个方向向量，不能表达空间中的特定位置。同时，法向量没有齐次坐标（顶点位置中的w分量）。这意味着，位移不应该影响到法向量。因此，如果我们打算把法向量乘以一个模型矩阵，我们就要从矩阵中移除位移部分，只选用模型矩阵左上角3×3的矩阵（注意，我们也可以把法向量的w分量设置为0，再乘以4×4矩阵；这同样可以移除位移）。对于法向量，我们只希望对它实施缩放和旋转变换。

如果模型矩阵执行了不等比缩放，顶点的改变会导致法向量不再垂直于表面了。因此，我们不能用这样的模型矩阵来变换法向量。

要修复不等比缩放导致的法线不再垂直于表面，可以使用法线矩阵来移除对法向量错误缩放的影响。

法线矩阵被定义为「模型矩阵左上角3x3部分的逆矩阵的转置矩阵」。
** 材质
想要在OpenGL中模拟多种类型的物体，我们必须针对每种表面定义不同的材质(Material)属性。

当描述一个表面时，我们可以分别为三个光照分量定义一个材质颜色(Material Color)：环境光照(Ambient Lighting)、漫反射光照(Diffuse Lighting)和镜面光照(Specular Lighting)。通过为每个分量指定一个颜色，我们就能够对表面的颜色输出有细粒度的控制了。
